version: '3.3'
services:
  blockchain:
    build:
      context: ./blockchain
    ports:
      - "8080:8080"
  app:
    build:
      context: ./frontend_app
    ports:
      - "3000:3000"
    environment:
      - CI=true
