version: '3.3'
services:
  blockchain:
    build:
      context: .
    ports:
      - "4000:4000"
      - "5000:5000"
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - LISK_API_PUBLIC=true
